// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MatchClockController from "./match_clock_controller"
application.register("match-clock", MatchClockController)

import LiveMatchesModalController from "./live_matches_modal_controller"
application.register("live-matches-modal", LiveMatchesModalController)
